
// Agents

export const FETCH_ORGANIZATIONS = 'FETCH_ORGANIZATIONS';
export const FETCH_BRANCHES = 'FETCH_BRANCHES';
export const UPDATE_ORGANIZATION = 'UPDATE_ORGANIZATION';
export const UPDATE_ORGANIZATION_ID = 'UPDATE_ORGANIZATION_ID';
export const UPDATE_BRANCH = 'UPDATE_BRANCH';
export const UPDATE_BRANCH_ID = 'UPDATE_BRANCH_ID';
export const UPDATE_ENDPOINT_IDENTITY = 'UPDATE_ENDPOINT_IDENTITY';
export const UPDATE_SETUP_STATUS = 'UPDATE_SETUP_STATUS';
export const FETCH_ENVRONMENT_CONTROL = 'FETCH_ENVRONMENT_CONTROL';

export const LISTEN_AGENTS_START = 'LISTEN_AGENTS_START';
export const LISTEN_AGENTS_CREATE = 'LISTEN_AGENTS_CREATE';
export const LISTEN_AGENTS_UPDATE = 'LISTEN_AGENTS_UPDATE';
export const LISTEN_AGENTS_DELETE = 'LISTEN_AGENTS_DELETE';

export const FETCH_AGENTS = 'FETCH_AGENTS';
export const AUTHENTICATE_AGENT = 'AUTHENTICATE_AGENT';
export const UNAUTHENTICATE_AGENT = 'UNAUTHENTICATE_AGENT';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

export const SAVE_WINDOW_FOCUS = 'SAVE_WINDOW_FOCUS';

// Sessions
export const LISTEN_SESSIONS_START = 'LISTEN_SESSIONS_START';
export const LISTEN_SESSIONS_UPDATE = 'LISTEN_SESSIONS_UPDATE';
export const LISTEN_SESSIONS_CREATE = 'LISTEN_SESSIONS_CREATE';
export const LISTEN_SESSIONS_DELETE = 'LISTEN_SESSIONS_DELETE';
export const FETCH_SESSIONS = 'FETCH_SESSIONS';
export const CREATE_SESSION = 'CREATE_SESSION';
export const CREATE_SESSION_LOG = 'CREATE_SESSION_LOG';

// Counters
export const LISTEN_COUNTERS_START = 'LISTEN_COUNTERS_START';
export const LISTEN_COUNTERS_CREATE = 'LISTEN_COUNTERS_CREATE';
export const LISTEN_COUNTERS_UPDATE = 'LISTEN_COUNTERS_UPDATE';
export const LISTEN_COUNTERS_DELETE = 'LISTEN_COUNTERS_DELETE';
export const FETCH_COUNTERS = 'FETCH_COUNTERS';
export const STORE_SIGNIN_COUNTERID = 'STORE_SIGNIN_COUNTERID';

// Tickets
// get and listen to tickets
export const LISTEN_TICKETS_START = 'LISTEN_TICKETS_START';
export const LISTEN_TICKETS_CREATE = 'LISTEN_TICKETS_CREATE';
export const LISTEN_TICKETS_UPDATE = 'LISTEN_TICKETS_UPDATE';
export const LISTEN_TICKETS_DELETE = 'LISTEN_TICKETS_DELETE';
export const FETCH_TICKETS = 'FETCH_TICKETS';
export const UPDATE_ACTIVE_TICKET = 'UPDATE_ACTIVE_TICKET';
export const INCREASE_TICKET_COUNT = 'INCREASE_TICKET_COUNT';
export const SAVE_LATEST_TICKET = 'SAVE_LATEST_TICKET';
export const UPDATE_ACTIVE_MANAGEMENT_TICKET = 'UPDATE_ACTIVE_MANAGEMENT_TICKET';

// managing a ticket
export const CALL_TICKET = 'CALL_TICKET';
export const COMPLETE_TICKET = 'COMPLETE_TICKET';
export const TRANSFER_TICKET = 'TRANSFER_TICKET';
export const NO_SHOW_TICKET = 'NO_SHOW_TICKET';

    // Sync total callTicekts made back to the app. 
    // This is required an usefull for tracking how many times a ticket is called 
    // and how long an agent waits before moving on. 
    // Also allows other agents to know which agents are calling tickets
export const LISTEN_CALL_TICKETS_SYNC_START = 'LISTEN_CALL_TICKETS_SYNC_START';
export const LISTEN_CALL_TICKETS_SYNC_CREATE = 'LISTEN_CALL_TICKETS_SYNC_CREATE';
export const FETCH_CALL_TICKETS = 'FETCH_CALL_TICKETS';

    // same as Sync total callTicekts but for transfers.
export const LISTEN_TRANSFER_TICKETS_SYNC_START = 'LISTEN_TRANSFER_TICKETS_SYNC_START';
export const LISTEN_TRANSFER_TICKETS_SYNC_CREATE = 'LISTEN_TRANSFER_TICKETS_SYNC_CREATE';
export const FETCH_TRANSFER_TICKETS = 'FETCH_TRANSFER_TICKETS';


// Services
export const LISTEN_SERVICES_START = 'LISTEN_SERVICES_START';
export const LISTEN_SERVICES_CREATE = 'LISTEN_SERVICES_CREATE';
export const LISTEN_SERVICES_UPDATE = 'LISTEN_SERVICES_UPDATE';
export const LISTEN_SERVICES_DELETE = 'LISTEN_SERVICES_DELETE';
export const FETCH_SERVICES = 'FETCH_SERVICES';

// Customers
export const LISTEN_CUSTOMERS_START = 'LISTEN_CUSTOMERS_START';
export const LISTEN_CUSTOMERS_CREATE = 'LISTEN_CUSTOMERS_CREATE';
export const LISTEN_CUSTOMERS_UPDATE = 'LISTEN_CUSTOMERS_UPDATE';
export const LISTEN_CUSTOMERS_DELETE = 'LISTEN_CUSTOMERS_DELETE';
export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';

// settings
export const MODAL_UPDATE = 'MODAL_UPDATE';
export const UPDATE_CURRENT_APP = 'UPDATE_CURRENT_APP';

//admin
export const FETCH_USERS = 'FETCH_USERS';